import { Link, NavLink } from 'react-router-dom'
import { ArrowRight, Check, CircleHelp, Leaf, Menu, X } from 'lucide-react'
import { useState } from 'react'

export function Navbar() {
  const [open, setOpen] = useState(false)
  return <header className="nav"><Link className="brand" to="/"><span className="brand-mark"><Leaf size={19} /></span><span>AgriVision</span></Link><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button><nav className={open ? 'nav-links open' : 'nav-links'}>{[['/', 'Home'], ['/analysis', 'How it works'], ['/about', 'About']].map(([to, label]) => <NavLink key={to} to={to} onClick={() => setOpen(false)}>{label}</NavLink>)}<Link className="button button-small" to="/analysis">Start analysis <ArrowRight size={16} /></Link></nav></header>
}

export function Page({ eyebrow, title, description, children }) { return <main className="page"><div className="page-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{description && <p>{description}</p>}</div>{children}</main> }
export function Field({ label, children, hint }) { return <label className="field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label> }
export function SectionTitle({ number, title, description }) { return <div className="section-title"><span className="section-number">{number}</span><div><h2>{title}</h2>{description && <p>{description}</p>}</div></div> }
export function EmptyState({ title = 'Data will appear here', text = 'Connect the backend service to populate this panel.' }) { return <div className="empty"><CircleHelp size={20} /><div><strong>{title}</strong><p>{text}</p></div></div> }
export function Loading() { return <div className="loading-container" role="status" aria-label="Loading"><div className="loading-loader"><svg viewBox="0 0 800 500" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="loading-chip" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3c6045" /><stop offset="100%" stopColor="#17231d" /></linearGradient><linearGradient id="loading-text" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f2f7ed" /><stop offset="100%" stopColor="#9bb39a" /></linearGradient></defs><g className="loading-traces"><path d="M100 100 H200 V210 H326" className="trace-bg" /><path d="M100 100 H200 V210 H326" className="trace-flow loading-purple" /><path d="M80 180 H180 V230 H326" className="trace-bg" /><path d="M80 180 H180 V230 H326" className="trace-flow loading-blue" /><path d="M60 260 H150 V250 H326" className="trace-bg" /><path d="M60 260 H150 V250 H326" className="trace-flow loading-yellow" /><path d="M100 350 H200 V270 H326" className="trace-bg" /><path d="M100 350 H200 V270 H326" className="trace-flow loading-green" /><path d="M700 90 H560 V210 H474" className="trace-bg" /><path d="M700 90 H560 V210 H474" className="trace-flow loading-blue" /><path d="M740 160 H580 V230 H474" className="trace-bg" /><path d="M740 160 H580 V230 H474" className="trace-flow loading-green" /><path d="M720 250 H590 V250 H474" className="trace-bg" /><path d="M720 250 H590 V250 H474" className="trace-flow loading-red" /><path d="M680 340 H570 V270 H474" className="trace-bg" /><path d="M680 340 H570 V270 H474" className="trace-flow loading-yellow" /></g><rect x="330" y="190" width="140" height="100" rx="20" fill="url(#loading-chip)" stroke="#284530" strokeWidth="3" /><text x="400" y="240" fontFamily="Arial, sans-serif" fontSize="22" fill="url(#loading-text)" textAnchor="middle" alignmentBaseline="middle">Loading</text><g className="loading-pins"><path d="M322 210h-10M322 230h-10M322 250h-10M322 270h-10M478 210h10M478 230h10M478 250h10M478 270h10" /></g></svg></div></div> }
export function StatusRow({ icon, label, complete, to }) { return <div className="status-row"><span className={complete ? 'status-icon complete' : 'status-icon'}>{complete ? <Check size={15} /> : icon}</span><span>{label}</span><span className={complete ? 'status-text ready' : 'status-text'}>{complete ? 'Completed' : 'Not provided'}</span><Link to={to} className="text-link">Edit</Link></div> }
export function Footer() { return <footer><span className="brand"><span className="brand-mark"><Leaf size={16} /></span>AgriVision</span><span>Smart decisions for stronger harvests.</span></footer> }
